parameters:
    flo_ascultaici.google_email: '194562557751-pqicjn4f2mibtohrnrlno0pth87fua58@developer.gserviceaccount.com'
    flo_ascultaici.google_client_id: '194562557751-pqicjn4f2mibtohrnrlno0pth87fua58.apps.googleusercontent.com'
    flo_ascultaici.google_scopes: [ 'https://www.googleapis.com/auth/youtube.readonly' ]
    flo_ascultaici.google_key_file: '/home/vagrant/google.json'

services:

    # repositories

    flo_ascultaici.repository.track:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\TrackRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Track ]

    flo_ascultaici.repository.playlist:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\PlaylistRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Playlist ]

    flo_ascultaici.repository.playlist_tagging:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Tag\PlaylistTaggingRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Tag\PlaylistTagging ]

    flo_ascultaici.repository.tag:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Tag\TagRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Tag\Tag ]

    flo_ascultaici.repository.tagging:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Tag\TaggingRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Tag\Tagging ]

    flo_ascultaici.repository.track_tagging:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Tag\TrackTaggingRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Tag\TrackTagging ]

    flo_ascultaici.repository.url_tagging:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Tag\UrlTaggingRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Tag\UrlTagging ]

    flo_ascultaici.repository.url:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Url\UrlRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Url\Url ]

    flo_ascultaici.repository.url_mixcloud:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Url\UrlMixcloudRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Url\UrlMixcloud ]

    flo_ascultaici.repository.url_soundcloud:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Url\UrlSoundcloudRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Url\UrlSoundcloud ]

    flo_ascultaici.repository.url_youtube:
        parent: flo_fictionary.repository.abstract
        class: Flo\Bundle\AscultaiciBundle\Repository\Url\UrlYoutubeRepository
        arguments: [ Flo\Bundle\AscultaiciBundle\Entity\Url\UrlYoutube ]


    # validators

    flo_ascultaici.validator.url.youtube:
        class: Flo\Bundle\AscultaiciBundle\Validator\Constraint\UrlYoutubeValidator
        tags:
            - { name: validator.constraint_validator, alias: url_youtube }

    # handlers

    flo_ascultaici.api_crawler:
        class: Flo\Bundle\AscultaiciBundle\Service\ApiCrawler
        arguments: [ @flo_ascultaici.repository.url ]

    flo_ascultaici.api.youtube:
        class: Flo\Bundle\AscultaiciBundle\Service\Api\Adapter\YoutubeProvider
        arguments: [ %flo_ascultaici.google_email%, %flo_ascultaici.google_key_file%, %flo_ascultaici.google_scopes% ]
