flo_ascultaici_backend:
    resource: "@FloAscultaiciBackendBundle/Resources/config/routing.yml"
    prefix:   /ascultaici/admin

flo_ascultaici:
    resource: "@FloAscultaiciBundle/Resources/config/routing.yml"
    prefix:   /ascultaici

flo_fictionary:
    resource: "@FloFictionaryBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: @FloUserBundle/Resources/config/routing_users.yml
    prefix: /
