ascultaici_playlist:
    path:     /
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:list" }

ascultaici_playlist_show:
    path:     /{slug}/show
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:show" }

ascultaici_playlist_new:
    path:     /new
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:new" }

ascultaici_playlist_create:
    path:     /create
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:create" }
    methods:  POST

ascultaici_playlist_edit:
    path:     /{slug}/edit
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:edit" }

ascultaici_playlist_update:
    path:     /{slug}/update
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:update" }
    methods:  [POST, PUT]

ascultaici_playlist_delete:
    path:     /{slug}/delete
    defaults: { _controller: "FloAscultaiciBackendBundle:Playlist:delete" }
    methods:  [POST, DELETE]

ascultaici_track_new:
    path: /{playlistSlug}/add-track
    defaults: { _controller: "FloAscultaiciBackendBundle:Track:new" }

ascultaici_track_create:
    path:     /{playlistSlug}/create
    defaults: { _controller: "FloAscultaiciBackendBundle:Track:create" }
    methods:  POST
