services:
    flo_ascultaici.handler.save.track:
        class: Flo\Bundle\AscultaiciBackendBundle\TrackSaveHandler
        arguments:
            - @flo_ascultaici.repository.track
            - @flo_ascultaici.repository.playlist
            - @flo_ascultaici.repository.url
